//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodSugar
    {
        public int SugarId { get; set; }
        public System.DateTime SugarDate { get; set; }
        public int SugarConcen { get; set; }
        public int MeasuredId { get; set; }
    
        public virtual Measured Measured { get; set; }
    }
}
