//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressure
    {
        public int BpId { get; set; }
        public System.DateTime BpDate { get; set; }
        public int Systolic_Pressure { get; set; }
        public int Diastolic_Pressure { get; set; }
        public int ChooseSideId { get; set; }
        public int PositionId { get; set; }
    
        public virtual ChooseSide ChooseSide { get; set; }
        public virtual Position Position { get; set; }
    }
}
