//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluseRate
    {
        public int PluseRateId { get; set; }
        public System.DateTime PluseRateDate { get; set; }
        public int PluseRateMeasure { get; set; }
    }
}
